/* A House Divided — endings. Resolver: hard stop if UNION <= 15 (E01).
   Otherwise, after Turn 8, first match by priority wins. */
(function () {
  window.AH_ENDINGS = [
    { id: 'E01', title: 'Two Republics', priority: 100,
      cond: { any: [{ flag: 'PEACEFUL_SEPARATION' }, { flag: 'CRITTENDEN' }, { meter: 'UNION', op: '<=', value: 15 }] },
      card: 'The map has two colors and a river between them. The United States and the Confederate States trade, glare, and arm. The Mississippi has tolls. Slavery expands into a Confederate Southwest and the Ledger keeps counting. There was no Antietam, no Proclamation, no Appomattox. There was also no 750,000 dead, and that is the argument people make on both sides of the river, for a century.',
      reality: 'Greeley’s "erring sisters," Scott’s "wayward sisters" letter and the Crittenden Compromise were all real proposals in 1860–61. Lincoln rejected them because separation or a guaranteed extension line would have made slavery permanent. Most historians think a peaceful separation would have produced a border war within a decade.',
      discuss: ['Was 750,000 dead the price of ending slavery, or could it have ended another way?', 'Who benefits from a peaceful separation, and who pays?'] },
    { id: 'E02', title: 'The Second War of Independence', priority: 95, cond: { flag: 'BRITISH_WAR' },
      card: 'Britain came in. Royal Navy squadrons broke the blockade, redcoats crossed from Canada, and the Union fought the world’s largest empire and the Confederacy at once. This world remembers 1862 the way the real one remembers 1812, and it never forgives London.',
      reality: 'The Trent Affair put 11,000 British troops on ships for Canada, and Palmerston’s cabinet drafted an ultimatum. Prince Albert softened it; Lincoln released the envoys with "one war at a time."',
      discuss: ['Why did Britain, which hated slavery, nearly go to war for the side that kept it?', 'How much of the war’s outcome was decided in London?'] },
    { id: 'E03', title: 'Cotton Empire', priority: 92, cond: { all: [{ flag: 'BRITISH_RECOGNITION' }, { meter: 'UNION', op: '<', value: 40 }] },
      card: 'Recognition came, the blockade broke, and the Confederacy has a seat at the table. It will spend fifty years discovering that a nation founded on one export and one labor system has no way to change either.',
      reality: 'The Confederacy’s foreign policy was recognition and it never came. Britain granted belligerent rights in May 1861 and nothing more. King Cotton failed because Britain had a two-year glut and India.',
      discuss: ['Why did the Confederacy believe cotton would force Europe’s hand?', 'Could the Confederacy have survived without expanding?'] },
    { id: 'E04', title: 'The Long War', priority: 90, cond: { flag: 'GUERRILLA_SOUTH' },
      card: 'The armies never surrendered. They dissolved into the hills, and the war became a hundred wars: bushwhackers, night riders, occupations. Reconstruction was a counterinsurgency and freedpeople were its first targets.',
      reality: 'In April 1865 Davis wanted to continue by partisan means; Lee refused, telling his officers to go home and plant crops. Missouri and Kansas had already shown what that war looked like.',
      discuss: ['Why did Lee refuse guerrilla war?', 'Who suffers most when armies dissolve?'] },
    { id: 'E05', title: 'Union Without Freedom', priority: 88, cond: { all: [{ flag: 'NO_EMANCIPATION' }, { meter: 'UNION', op: '>=', value: 60 }, { meter: 'FREEDOM', op: '<=', value: 20 }] },
      card: 'The Union was saved and nothing else was. No Proclamation, no Black regiments, no 13th Amendment. Four million people are still in the Ledger. The country is whole and it has learned nothing.',
      reality: 'This was Union policy through summer 1862: Lincoln told Greeley his object was to save the Union. The Confiscation Acts and the flood of contrabands made that position untenable.',
      discuss: ['Could the Union have won without emancipation?', 'What did enslaved people do to make this ending impossible?'] },
    { id: 'E06', title: 'The Copperhead Peace', priority: 86, cond: { any: [{ flag: 'ARMISTICE_1863' }, { flag: 'MCCLELLAN_1864' }] },
      card: 'The North got tired. An armistice, a convention, and an election that punished the men who had fought. The Wall between two Americas went up on the Ohio, and the Proclamation became a document about a country that no longer existed.',
      reality: 'In August 1864 Lincoln wrote that he expected to lose; the Democratic platform called the war a failure. Atlanta fell on Sept 2 and the election turned.',
      discuss: ['What made Northern voters tired, and what made them stop?', 'How do democracies fight long wars?'] },
    { id: 'E07', title: 'Forty Acres', priority: 84, cond: { all: [{ flag: 'LAND_REDISTRIBUTION' }, { flag: 'RADICAL_RECON_HOLDS' }] },
      card: 'The land was taken and given. The plantations of pardoned generals were divided among the people who had worked them, and the federal government stood behind the titles for a generation. It is the most different South in this game.',
      reality: 'Sherman’s Field Order 15 put 40,000 freedpeople on 400,000 acres; Johnson revoked it that autumn. Davis Bend ran as a freedmen’s colony for three years. Most historians agree the absence of land doomed Reconstruction.',
      discuss: ['Why did land matter more than the vote to the people who asked for it?', 'What is the difference between freedom and independence?'] },
    { id: 'E08', title: 'Lincoln Lives', priority: 82, cond: { flag: 'RICHMOND_1862' },
      card: 'Richmond fell in 1862. The war ended early, the Proclamation came as a peace measure, and Lincoln lived to serve a second term and manage a Reconstruction he had actually planned. He was certainly better at it than Johnson.',
      reality: 'McClellan’s Peninsula campaign reached seven miles from Richmond in June 1862 before Lee drove it back. Lincoln’s last speech endorsed Black suffrage for soldiers; Booth was in the audience.',
      discuss: ['How much of Reconstruction’s failure was Andrew Johnson?', 'Is a shorter war a better one?'] },
    { id: 'E09', title: 'The Border Burns', priority: 80, cond: { flag: 'KENTUCKY_CSA' },
      card: 'Kentucky went south, and the Ohio River became the front. Cincinnati dug trenches. The western campaigns came a year late, and the war was longer by exactly that much.',
      reality: 'Kentucky’s governor was Confederate in sympathy and its legislature Unionist; it declared neutrality on May 20, 1861. Lincoln called losing Kentucky "nearly the same as to lose the whole game."',
      discuss: ['Why was Kentucky worth more than any battle?', 'What made a state’s loyalty, when its people were split?'] },
    { id: 'E10', title: 'The Rehearsal of 1851', priority: 78, cond: { flag: 'SECESSION_1850' },
      card: 'South Carolina seceded alone in 1851 and nobody followed. After eight months the state came back with nothing. When the real crisis came in 1860, everyone remembered the rehearsal, and the Deep South hesitated.',
      reality: 'The Nashville Convention adopted secession resolutions; Mississippi’s Quitman lost a referendum in 1851; South Carolina’s 1852 convention declined to secede. Secession in 1850 failed for lack of partners.',
      discuss: ['Why did secession fail in 1851 and succeed in 1860?', 'Was the Compromise of 1850 a success, a delay, or both?'] },
    { id: 'E11', title: 'The Second Middle Passage', priority: 76, cond: { any: [{ flag: 'SLAVE_TRADE_REOPENED' }, { flag: 'CUBA_SEIZED' }, { flag: 'WALKER_EMPIRE' }] },
      card: 'The slave trade reopened, or Cuba fell, and the South got its empire. Ships from Ouidah unload in Charleston. The Ledger grows by tens of thousands a year. The empire is real and it has no friends.',
      reality: 'The Vicksburg Convention voted to reopen the African slave trade in 1859; the Wanderer landed 400 Africans in Georgia in 1858. All failed, mostly because the Upper South, the North and Britain had no interest in a Caribbean slave empire.',
      discuss: ['Why did the Deep South want to expand?', 'How did Britain’s navy shape American history?'] },
    { id: 'E12', title: 'Exodus', priority: 74, cond: { any: [{ flag: 'EMIGRATION' }, { flag: 'COLONIZATION' }] },
      card: 'They left. To Canada, Haiti, Liberia, Kansas. Some found freedom, many found fever, and the movement that stayed behind was smaller for it. Douglass said we are here to stay. Fewer people were.',
      reality: 'About 20,000–40,000 Black Americans lived in Canada by 1860; colonization as federal policy died when Black Americans refused it and Lincoln stopped proposing it after 1863.',
      discuss: ['Why did most Black Americans refuse to leave a country that denied them citizenship?', 'What is the difference between emigration and colonization?'] },
    { id: 'E13', title: 'A Nation Within', priority: 72, cond: { all: [{ flag: 'CHEROKEE_UNITED' }, { faction: 'CHR' }] },
      card: 'The Cherokee Nation made peace with itself before the Americans did, and went to Washington with one voice. It entered the twentieth century with a treasury, courts, and a generation’s more sovereignty than the real one.',
      reality: 'Two Cherokee delegations went to Washington in 1866, and the US used each against the other. Watie had been the last Confederate general to surrender; the Nation’s population had fallen by about a third.',
      discuss: ['Why did the US punish the loyal Cherokee for the Confederate treaty?', 'What did sovereignty mean for a nation inside the United States in 1866?'] },
    { id: 'E14', title: 'Maximilian’s America', priority: 70, cond: { flag: 'MAXIMILIAN_AXIS' },
      card: 'France’s emperor in Mexico had a Confederate neighbor, and the Union of 1865 found a million veterans with nowhere to go and a war on the Rio Grande. The Monroe Doctrine was enforced by artillery.',
      reality: 'Napoleon III installed Maximilian in 1864. After Appomattox, Grant sent 50,000 troops to the border; Napoleon withdrew in 1866 and Maximilian was shot in 1867.',
      discuss: ['How did the Civil War’s end change the Western Hemisphere?', 'What did the Monroe Doctrine mean before the US could enforce it?'] },
    { id: 'E15', title: 'The Confederate Emancipation', priority: 68, cond: { flag: 'CONFED_EMANCIPATION' },
      card: 'The Confederacy freed 200,000 men to fight for it, and in doing so admitted what the war was about. Most walked to Union lines at the first picket. The South lost anyway, with no Lost Cause to tell.',
      reality: 'Cleburne proposed arming and freeing enslaved men in Jan 1864; Davis suppressed the memo. In March 1865 two companies drilled in Richmond the week before it fell.',
      discuss: ['Why did the Confederacy refuse Cleburne?', 'What does it mean that the South’s last plan was emancipation?'] },
    { id: 'E16', title: 'The Redeemers', priority: 66, cond: { flag: 'LENIENT_RECON' },
      card: 'Johnson’s plan stood. No 14th Amendment, no Black suffrage, Southern states readmitted by 1866 with ex-Confederate generals in Congress and Black Codes on the books. The Ledger stopped counting people as property and started counting them as convicts.',
      reality: 'This was Reconstruction from May 1865 to spring 1866. The Black Codes and the Memphis and New Orleans massacres convinced Congress to override Johnson and pass the 14th Amendment.',
      discuss: ['What were the Black Codes and how did they work?', 'Why did the North turn against Johnson?'] },
    { id: 'E17', title: 'The Second Founding', priority: 64, cond: { all: [{ any: [{ flag: 'RADICAL_RECON_HOLDS' }, { flag: 'NEW_SOUTH_COOPERATES' }] }, { meter: 'FREEDOM', op: '>=', value: 55 }] },
      card: 'Reconstruction held. The 14th and 15th Amendments were enforced for a generation. Black legislatures wrote school laws and stayed to see them funded. The South of this world was poorer for a decade and freer for a century.',
      reality: 'Reconstruction governments held from 1867 to 1877 and did much of this. The North’s withdrawal in 1877 and the Court’s Cruikshank decision ended federal enforcement. The 15th Amendment stayed out of practice until 1965.',
      discuss: ['What did Reconstruction governments actually do?', 'What would it have cost to hold on, and who would have paid?'] },
    { id: 'E18', title: 'Compensated Freedom', priority: 62, cond: { flag: 'KENTUCKY_EMANCIPATES' },
      card: 'A border state took Lincoln’s offer. It freed its people gradually and was paid for it. The war ended slavery by two roads at once: force in the South, purchase in the border.',
      reality: 'Lincoln proposed compensated emancipation to the border states in 1862 at about $400 a person; every delegation refused. Kentucky and Delaware were the last states with legal slavery when the 13th Amendment took effect.',
      discuss: ['Why did the border states refuse money for something they were about to lose?', 'Who should have been compensated?'] },
    { id: 'E19', title: 'The Unfinished Revolution', priority: 60,
      cond: { any: [{ historicalPct: { op: '>=', value: 75 } }, { all: [{ meter: 'UNION', op: '>=', value: 60 }, { meter: 'FREEDOM', op: '>=', value: 25 }, { meter: 'FREEDOM', op: '<=', value: 45 }] }] },
      card: 'You made most of the calls the real leaders made. The war was won, slavery ended, three amendments were written, and then the country looked away. This ending is called unfinished because it was: the promises of 1868 and 1870 were kept in 1965.',
      reality: 'About 750,000 died. Four million people were freed. Federal troops left the South in 1877. Eric Foner called Reconstruction "America’s unfinished revolution"; the phrase is his.',
      discuss: ['Who won the Civil War? Ask a freedperson in 1866, in 1877, and in 1900.', 'Why does the country remember Appomattox better than Colfax?'] },
    { id: 'E20', title: 'Frozen Union', priority: 0, cond: { any: [{ meter: 'UNION', op: '>=', value: 0 }] },
      card: 'Nothing broke and nothing healed. Your path was careful and strange: the Union held, or mostly, and slavery ended, or mostly, and the questions the war was supposed to answer were postponed. This is the ending where the meters stayed in the middle.',
      reality: 'Most of the men who ran the country in 1850 expected exactly this: another compromise, another decade, the questions handed to their children. It was managed for ten years.',
      discuss: ['Can a country postpone a moral question indefinitely?', 'Which of your choices kept things frozen, and was that wisdom or avoidance?'] }
  ];
})();
